import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music Corner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main>
        <div className={styles.backgroundImage}>
                  <img className={styles.backgroundImage} src="images/homePageBackground.jpg"></img>
        </div>
      </main>
    </div>
  )
}
